apiVersion: v1
kind: Service
metadata:
  name: &service-name ms-frontend

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: *service-name
  ports:
    - name: http
      port: 80
      nodePort: 30100
  type: NodePort